import type { AgentEvent } from '@ari/contracts/agent-event'
import { formatUnknownError } from '@ari/shared/result'

/**
 * Maps `codex exec --json` JSONL lines onto normalized AgentEvents. Pure and
 * total: malformed lines surface as error events, never throws. The real
 * error fixture was recorded from codex CLI 0.5x; success item shapes follow
 * the documented thread event schema.
 */

interface CodexItem {
  id?: string
  type?: string
  text?: string
  command?: string
  aggregated_output?: string
  exit_code?: number
  status?: string
}

interface NativeLine {
  type?: string
  subtype?: string
  thread_id?: string
  message?: string
  error?: { message?: string } | string
  item?: CodexItem
  usage?: { input_tokens?: number; output_tokens?: number }
}

/** Reconnect chatter is transport noise, not a transcript-worthy failure. */
function isReconnectNoise(message: string): boolean {
  return message.startsWith('Reconnecting...')
}

export function mapCodexLine(line: string): AgentEvent[] {
  let parsed: NativeLine
  try {
    parsed = JSON.parse(line) as NativeLine
  } catch (e) {
    return [{ type: 'error', message: `unparseable line: ${formatUnknownError(e)}`, rawJson: null }]
  }

  switch (parsed.type) {
    case 'thread.started':
    case 'turn.started':
      return []

    case 'item.started':
    case 'item.updated': {
      const item = parsed.item
      if (!item?.id) return []
      if (parsed.type === 'item.started' && item.type === 'command_execution') {
        return [
          {
            type: 'tool-started',
            callId: item.id,
            name: 'bash',
            argsJson: JSON.stringify({ command: item.command ?? '' }),
          },
        ]
      }
      return []
    }

    case 'item.completed': {
      const item = parsed.item
      if (!item) return []
      switch (item.type) {
        case 'agent_message':
          return item.text ? [{ type: 'text-delta', text: item.text }] : []
        case 'reasoning':
          return item.text ? [{ type: 'thinking-delta', text: item.text }] : []
        case 'command_execution': {
          if (!item.id) return []
          const events: AgentEvent[] = []
          // exec --json may emit completed without a started line.
          events.push({
            type: 'tool-started',
            callId: item.id,
            name: 'bash',
            argsJson: JSON.stringify({ command: item.command ?? '' }),
          })
          events.push({
            type: 'tool-completed',
            callId: item.id,
            resultJson: JSON.stringify(item.aggregated_output ?? ''),
            isError: typeof item.exit_code === 'number' && item.exit_code !== 0,
          })
          return events
        }
        case 'file_change': {
          if (!item.id) return []
          return [
            {
              type: 'tool-completed',
              callId: item.id,
              resultJson: JSON.stringify(item),
              isError: item.status === 'failed',
            },
          ]
        }
        default:
          return []
      }
    }

    case 'error': {
      const message = parsed.message ?? ''
      if (isReconnectNoise(message)) return []
      return [{ type: 'error', message, rawJson: null }]
    }

    case 'turn.completed': {
      const usage = parsed.usage ?? {}
      return [
        {
          type: 'usage',
          inputTokens: typeof usage['input_tokens'] === 'number' ? (usage['input_tokens']) : 0,
          outputTokens:
            typeof usage['output_tokens'] === 'number' ? (usage['output_tokens']) : 0,
          costUsd: null,
        },
        { type: 'done' },
      ]
    }

    case 'turn.failed': {
      const err = parsed.error
      const message =
        typeof err === 'string' ? err : (err?.message ?? 'codex turn failed')
      return [
        { type: 'error', message, rawJson: null },
        { type: 'done' },
      ]
    }

    default:
      return []
  }
}

export function mapCodexStream(lines: Iterable<string>): AgentEvent[] {
  return Array.from(lines).flatMap((line) => mapCodexLine(line))
}

/**
 * Inbound frames of the `codex app-server` newline-delimited JSON-RPC
 * transport. Method names and payload shapes follow the protocol schema
 * generated by `codex app-server generate-json-schema` (codex-cli 0.149.0).
 */
export type AppServerInbound =
  | { kind: 'response'; id: number; result: unknown; events: [] }
  | { kind: 'error-response'; id: number; message: string; events: [] }
  | { kind: 'notification'; method: string; events: AgentEvent[] }
  | {
      /** Server→client request answered via its JSON-RPC request id. */
      kind: 'server-request'
      requestId: number
      method: string
      /** Present when the request is a supported approval prompt. */
      approvalId: string | null
      events: AgentEvent[]
    }

interface AppServerItem {
  id?: string
  type?: string
  text?: string
  command?: string
  aggregatedOutput?: string | null
  exitCode?: number | null
  status?: string
  tool?: string
  result?: unknown
  summary?: { text?: string }[] | null
  content?: { text?: string }[] | null
}

/** Stateful mapper: one instance per connection, fed every inbound line. */
export interface AppServerMapper {
  mapLine(line: string): AppServerInbound
}

/**
 * Maps raw app-server JSON-RPC lines onto normalized events plus routing
 * metadata. Pure with respect to the wire: malformed lines surface as error
 * events instead of throwing. Deltas and item completions are de-duplicated
 * so servers that stream both do not double-render.
 */
export function createAppServerMapper(): AppServerMapper {
  const deltaSeen = new Set<string>()
  const startedItems = new Set<string>()

  function itemEvents(item: AppServerItem, complete: boolean): AgentEvent[] {
    if (!item || typeof item !== 'object') return []
    const callId = item.id ?? ''
    switch (item.type) {
      case 'agentMessage': {
        if (!complete) return []
        if (callId && deltaSeen.has(callId)) return []
        return item.text ? [{ type: 'text-delta', text: item.text }] : []
      }
      case 'reasoning': {
        if (!complete) return []
        if (callId && deltaSeen.has(callId)) return []
        const text = reasoningText(item)
        return text ? [{ type: 'thinking-delta', text }] : []
      }
      case 'commandExecution': {
        if (!callId) return []
        const events: AgentEvent[] = []
        if (!complete && !startedItems.has(callId)) {
          startedItems.add(callId)
          events.push({
            type: 'tool-started',
            callId,
            name: 'bash',
            argsJson: JSON.stringify({ command: item.command ?? '' }),
          })
        }
        if (complete) {
          // Completions may arrive without a started line.
          if (!startedItems.has(callId)) {
            startedItems.add(callId)
            events.push({
              type: 'tool-started',
              callId,
              name: 'bash',
              argsJson: JSON.stringify({ command: item.command ?? '' }),
            })
          }
          events.push({
            type: 'tool-completed',
            callId,
            resultJson: JSON.stringify(item.aggregatedOutput ?? ''),
            isError:
              item.status === 'failed' ||
              (typeof item.exitCode === 'number' && item.exitCode !== 0),
          })
        }
        return events
      }
      case 'fileChange': {
        if (!callId) return []
        const events: AgentEvent[] = []
        if (!startedItems.has(callId)) {
          startedItems.add(callId)
          events.push({
            type: 'tool-started',
            callId,
            name: 'file-change',
            argsJson: '{}',
          })
        }
        if (complete) {
          events.push({
            type: 'tool-completed',
            callId,
            resultJson: JSON.stringify(item),
            isError: item.status === 'failed',
          })
        }
        return events
      }
      case 'mcpToolCall': {
        if (!callId) return []
        const events: AgentEvent[] = []
        if (!startedItems.has(callId)) {
          startedItems.add(callId)
          events.push({
            type: 'tool-started',
            callId,
            name: item.tool ?? 'mcp-tool',
            argsJson: '{}',
          })
        }
        if (complete) {
          events.push({
            type: 'tool-completed',
            callId,
            resultJson: JSON.stringify(item.result ?? item),
            isError: item.status === 'failed',
          })
        }
        return events
      }
      default:
        return []
    }
  }

  return {
    mapLine(line: string): AppServerInbound {
      let frame: Record<string, unknown>
      try {
        frame = JSON.parse(line) as Record<string, unknown>
      } catch (e) {
        return {
          kind: 'notification',
          method: '',
          events: [
            { type: 'error', message: `unparseable frame: ${formatUnknownError(e)}`, rawJson: null },
          ],
        }
      }

      const hasId = typeof frame['id'] === 'number' || typeof frame['id'] === 'string'
      const method = typeof frame['method'] === 'string' ? frame['method'] : null

      if (method === null && hasId) {
        const error = frame['error'] as { message?: string } | undefined
        if (error !== undefined && error !== null) {
          return {
            kind: 'error-response',
            id: frame['id'] as number,
            message: typeof error['message'] === 'string' ? error['message'] : 'codex rpc error',
            events: [],
          }
        }
        return { kind: 'response', id: frame['id'] as number, result: frame['result'] ?? null, events: [] }
      }

      const params = (frame['params'] ?? {}) as Record<string, unknown>
      if (method !== null && hasId) {
        // Server→client request; today only approval prompts are supported.
        const approval = approvalEvent(method, params)
        return {
          kind: 'server-request',
          requestId: frame['id'] as number,
          method,
          approvalId: approval?.approvalId ?? null,
          events: approval ? [approval.event] : [],
        }
      }

      return { kind: 'notification', method: method ?? '', events: notificationEvents(method, params, deltaSeen, itemEvents) }
    },
  }
}

function reasoningText(item: AppServerItem): string {
  const parts = [...(item.summary ?? []), ...(item.content ?? [])]
  return parts
    .map((p) => (typeof p?.text === 'string' ? p.text : ''))
    .filter((t) => t.length > 0)
    .join('\n')
}

function approvalEvent(
  method: string,
  params: Record<string, unknown>,
): { approvalId: string; event: AgentEvent } | null {
  if (
    method !== 'item/commandExecution/requestApproval' &&
    method !== 'item/fileChange/requestApproval'
  ) {
    return null
  }
  const approvalId = approvalRef(params)
  const toolName =
    method === 'item/commandExecution/requestApproval'
      ? 'bash'
      : 'file-change'
  const summary: Record<string, unknown> = {}
  for (const key of ['command', 'cwd', 'reason', 'grantRoot', 'itemId']) {
    if (params[key] !== undefined && params[key] !== null) summary[key] = params[key]
  }
  return {
    approvalId,
    event: {
      type: 'approval-requested',
      approvalId,
      toolName,
      summaryJson: JSON.stringify(summary),
    },
  }
}

/** Deterministic Ari-side approval id anchored on the server item id. */
export function approvalRef(params: Record<string, unknown>): string {
  const itemId = params['itemId']
  return `codex-appr-${typeof itemId === 'string' && itemId.length > 0 ? itemId : 'unknown'}`
}

function notificationEvents(
  method: string | null,
  params: Record<string, unknown>,
  deltaSeen: Set<string>,
  itemEvents: (item: AppServerItem, complete: boolean) => AgentEvent[],
): AgentEvent[] {
  switch (method) {
    case 'thread/started': {
      const ref =
        typeof params['threadId'] === 'string'
          ? params['threadId']
          : ((params['thread'] as { id?: unknown } | undefined)?.['id'] as string | undefined)
      return typeof ref === 'string' && ref.length > 0 ? [{ type: 'session-ref', ref }] : []
    }
    case 'item/agentMessage/delta':
    case 'item/reasoning/summaryTextDelta':
    case 'item/reasoning/textDelta': {
      const itemId = typeof params['itemId'] === 'string' ? params['itemId'] : ''
      const delta = typeof params['delta'] === 'string' ? params['delta'] : ''
      if (delta.length === 0) return []
      if (itemId) deltaSeen.add(itemId)
      return [
        method.startsWith('item/reasoning/')
          ? { type: 'thinking-delta', text: delta }
          : { type: 'text-delta', text: delta },
      ]
    }
    case 'item/started':
    case 'item/completed': {
      const item = params['item'] as AppServerItem | undefined
      return itemEvents(item ?? {}, method === 'item/completed')
    }
    case 'thread/tokenUsage/updated': {
      const usage = params['tokenUsage'] as
        | { total?: { inputTokens?: number; outputTokens?: number } }
        | undefined
      const total = usage?.total ?? {}
      return [
        {
          type: 'usage',
          inputTokens: typeof total['inputTokens'] === 'number' ? total['inputTokens'] : 0,
          outputTokens: typeof total['outputTokens'] === 'number' ? total['outputTokens'] : 0,
          costUsd: null,
        },
      ]
    }
    case 'turn/completed': {
      const turn = params['turn'] as
        | { status?: string; error?: { message?: string } | null }
        | undefined
      if (turn?.status === 'failed') {
        return [
          { type: 'error', message: turn.error?.message ?? 'codex turn failed', rawJson: null },
          { type: 'done' },
        ]
      }
      return [{ type: 'done' }]
    }
    case 'error': {
      const error = params['error'] as { message?: string } | undefined
      const willRetry = params['willRetry'] === true
      if (willRetry) return []
      return [{ type: 'error', message: error?.message ?? 'codex error', rawJson: null }]
    }
    default:
      return []
  }
}
