/**
 * Injected into the guest page. Built from line arrays so the main bundle
 * never carries a multi-line template literal (esbuild CJS shims split those).
 */
function script(lines: string[]): string {
  return lines.join('\n')
}

export const PICKER_SOURCE = script([
  'new Promise((resolve) => {',
  '  window.__ariCancelPick && window.__ariCancelPick()',
  "  const box = document.createElement('div')",
  "  box.setAttribute('data-ari-pick', '1')",
  "  box.style.cssText = 'position:fixed;z-index:2147483647;pointer-events:none;border:2px solid #7c6cf0;background:rgba(124,108,240,.12);border-radius:4px;'",
  '  document.documentElement.appendChild(box)',
  '  function cssPath(el) {',
  '    if (el.id) {',
  "      const id = '#' + CSS.escape(el.id)",
  '      try { if (document.querySelectorAll(id).length === 1) return id } catch (e) {}',
  '    }',
  '    const parts = []',
  '    let cur = el',
  '    for (let i = 0; i < 5 && cur && cur.nodeType === 1 && cur !== document.documentElement; i++) {',
  '      let part = cur.tagName.toLowerCase()',
  '      if (cur.classList && cur.classList.length) {',
  "        part += '.' + Array.from(cur.classList).slice(0, 2).map(function(c) { return CSS.escape(c) }).join('.')",
  '      }',
  '      const parent = cur.parentElement',
  '      if (parent) {',
  '        const same = Array.from(parent.children).filter(function(c) { return c.tagName === cur.tagName })',
  "        if (same.length > 1) part += ':nth-of-type(' + (same.indexOf(cur) + 1) + ')'",
  '      }',
  '      parts.unshift(part)',
  '      cur = parent',
  '    }',
  "    return parts.join(' > ')",
  '  }',
  '  function targetOf(event) {',
  '    const el = document.elementFromPoint(event.clientX, event.clientY)',
  '    if (!el || el === box) return null',
  '    return el',
  '  }',
  '  function cleanup() {',
  '    window.__ariCancelPick = undefined',
  "    window.removeEventListener('mousemove', onMove, true)",
  "    window.removeEventListener('click', onClick, true)",
  "    window.removeEventListener('keydown', onKey, true)",
  '    box.remove()',
  '  }',
  '  function onMove(event) {',
  '    const el = targetOf(event)',
  '    if (!el) return',
  '    const r = el.getBoundingClientRect()',
  "    box.style.left = r.left + 'px'",
  "    box.style.top = r.top + 'px'",
  "    box.style.width = r.width + 'px'",
  "    box.style.height = r.height + 'px'",
  '  }',
  '  function onClick(event) {',
  '    event.preventDefault()',
  '    event.stopPropagation()',
  '    const el = targetOf(event)',
  '    cleanup()',
  '    if (!el) { resolve(null); return }',
  '    const r = el.getBoundingClientRect()',
  '    resolve({',
  '      url: location.href,',
  '      selector: cssPath(el),',
  '      tag: el.tagName.toLowerCase(),',
  "      text: (el.innerText || el.value || '').trim().slice(0, 400),",
  "      role: el.getAttribute('role'),",
  "      ariaLabel: el.getAttribute('aria-label'),",
  "      html: (el.outerHTML || '').slice(0, 1500),",
  '      x: r.x, y: r.y, width: r.width, height: r.height',
  '    })',
  '  }',
  '  function onKey(event) {',
  "    if (event.key === 'Escape') { event.preventDefault(); cleanup(); resolve(null) }",
  '  }',
  '  window.__ariCancelPick = function() { cleanup(); resolve(null) }',
  "  window.addEventListener('mousemove', onMove, true)",
  "  window.addEventListener('click', onClick, true)",
  "  window.addEventListener('keydown', onKey, true)",
  '})',
])

export const CANCEL_PICK_SOURCE =
  'void (window.__ariCancelPick && window.__ariCancelPick())'

export const SNAPSHOT_SOURCE = script([
  '(function() {',
  '  function cssPath(el) {',
  '    if (el.id) {',
  "      const id = '#' + CSS.escape(el.id)",
  '      try { if (document.querySelectorAll(id).length === 1) return id } catch (e) {}',
  '    }',
  '    const parts = []',
  '    let cur = el',
  '    for (let i = 0; i < 4 && cur && cur.nodeType === 1 && cur !== document.documentElement; i++) {',
  '      let part = cur.tagName.toLowerCase()',
  '      if (cur.classList && cur.classList.length) {',
  "        part += '.' + Array.from(cur.classList).slice(0, 2).map(function(c) { return CSS.escape(c) }).join('.')",
  '      }',
  '      parts.unshift(part)',
  '      cur = cur.parentElement',
  '    }',
  "    return parts.join(' > ')",
  '  }',
  "  const nodes = Array.from(document.querySelectorAll('a,button,input,textarea,select,[role=button],[role=link]')).slice(0, 80)",
  '  return {',
  '    url: location.href,',
  '    title: document.title,',
  "    text: (document.body && document.body.innerText ? document.body.innerText : '').slice(0, 4000),",
  '    elements: nodes.map(function(el) {',
  '      return {',
  '        tag: el.tagName.toLowerCase(),',
  '        selector: cssPath(el),',
  "        text: ((el.innerText || el.getAttribute('aria-label') || el.getAttribute('placeholder') || '') + '').trim().slice(0, 80)",
  '      }',
  '    })',
  '  }',
  '})()',
])
