import type { RpcMethod } from '@ari/contracts/rpc'

/**
 * Every RPC method the renderer can reach. The RpcRegistry validates
 * payloads, but `ipcMain.handle` is registered per-method from this list —
 * a method missing here is silently unreachable from the renderer even when
 * its registry handler exists (that is exactly how `project.move` first
 * shipped dead). The guard test pins this list to the contracts channel map.
 */
export const IPC_METHODS = [
  'ping',
  'app.info',
  'session.list',
  'session.create',
  'session.load',
  'session.workspace',
  'session.destroy',
  'sessions.importable',
  'sessions.import',
  'usage.summary',
  'providers.allowance',
  'usage.ccusage',
  'command.dispatch',
  'attachments.stage',
  'attachments.read',
  'providers.detect',
  'providers.models',
  'providers.plan',
  'providers.install',
  'providers.cancelInstall',
  'providers.authProbe',
  'providers.login',
  'providers.configFiles',
  'providers.readConfig',
  'providers.writeConfig',
  'window.minimize',
  'window.toggleMaximize',
  'window.close',
  'theme.apply',
  'terminal.create',
  'terminal.write',
  'terminal.resize',
  'terminal.kill',
  'project.list',
  'project.add',
  'project.open',
  'project.close',
  'project.remove',
  'project.move',
  'dialog.pickFolder',
  'shell.revealPath',
  'shell.openUrl',
  'files.index',
  'search.content',
  'endpoints.list',
  'endpoints.upsert',
  'endpoints.remove',
  'endpoints.test',
  'endpoints.discoverModels',
  'endpoints.setModels',
  'settings.get',
  'settings.update',
  'git.status',
  'git.diffWorktree',
  'git.turnDiff',
  'git.add',
  'git.commit',
  'git.push',
  'git.createPr',
  'plan.get',
  'scripts.list',
  'fs.list',
  'fs.readTextFile',
  'fs.writeTextFile',
  'stream.subscribe',
  'stream.unsubscribe',
] as const satisfies readonly RpcMethod[]
